/**
 * Copyright (c) 2003-2017, Great Software Laboratory Pvt. Ltd. The software in this package is published under the terms of the Commercial Free Software license V.1, a copy of which has been included with this distribution in the LICENSE.md file.
 */
package org.mule.extension.elastic.index;

import static org.junit.Assert.assertTrue;

import org.elasticsearch.client.indices.CreateIndexResponse;
import org.junit.After;
import org.junit.Test;
import org.mule.functional.junit4.MuleArtifactFunctionalTestCase;

/**
 * @author Great Software Laboratory Pvt. Ltd.
 *
 */
public class CreateIndexOperationTestCase extends MuleArtifactFunctionalTestCase {

    @Override
    protected String getConfigFile() {
        return "testElasticsearchOperations.xml";
    }

    /**
     * Remove the resources generated by the operation
     */
    @After
    public void tearDown() {
        try {
            flowRunner("testDeleteIndexFlow").run().getMessage().getPayload().getValue();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * Test the operation
     */
    @Test
    public void executeCreateIndexOperation() {

        CreateIndexResponse payloadValue;
        try {
            payloadValue = ((CreateIndexResponse) flowRunner("testCreateIndexFlow").run().getMessage().getPayload().getValue());
            assertTrue(payloadValue.isShardsAcknowledged() == true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}